apiVersion: v1
kind: Pod
metadata:
  name: envs
spec:
  containers:
  - name: simpleservice
    image: gajjelli/simpleservice
    ports:
    - containerPort: 9876
    env:
    - name: SIMPLE_SERVICE_VERSION
      value: "1.0"
