apiVersion: v1
kind: Pod
metadata:
  name: error-pod
spec:
  containers:
  - name: sise
    image: gajjelli/simpleservice
    ports:
    - containerPort: 9876
    env:
    - name: HEALTH_MIN
      value: "1000"
    - name: HEALTH_MAX
      value: "4000"
    livenessProbe:
      initialDelaySeconds: 2
      periodSeconds: 5
      httpGet:
        path: /health
        port: 9876
