apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 2Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    path: /var/nfs/kube-nfs
    server: 192.168.146.199
