apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: siservice-dep
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: siservice-py-label
    spec:
      containers:
      - name: siservice
        image: gajjelli/simpleservice
        ports:
        - containerPort: 9876
      - name: centshell
        image: centos:7
        command:
          - "bin/bash"
          - "-c"
          - "sleep 10000"
