apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mongo-pv
spec:
  capacity:
    storage: 2Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    # FIXME: use the right IP
    path: /opt/data/mongo/vol/0
    server: 192.168.146.199
